services:
  db:
   image: postgres:13.4-alpine
   container_name: postgres
   ports:
      - 5432:5432
   volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
   environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: jiradb
      PGDATA: /var/lib/postgresql/data/pgdata
   restart: always
  jira:
   image: atlassian/jira-software:latest
   container_name: jira
   ports:
      - 8080:8080
   volumes:
      - ./jira:/var/atlassian/application-data/jira
   environment:
      POSTGRES_HOST: db
   restart: always
   links:
      - db
  nginx:
   image: nginx:1.21.3-alpine
   container_name: nginx
   volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
   links:
      - jira
   ports:
      - 80:80
   restart: always

